### ISSUE TITLE
请问超图内部的是不是使用的不是s3m-sdk来生成转换s3m的？

### ISSUE THREAD

**Issue by elfc2000** [SuperMap/s3m-spec#100]
因为我使用了同样的3dtiles数据，一份是超图desktop转的，一个是用这个sdk转的。我发现了还是有比较大差异，显著的就是scp的json组织顺序不同？
![微信图片_20241129161831](https://github.com/user-attachments/assets/7e063a97-42a6-49a9-ac24-7b3f0265fbf8)

**Comment by heqianhq** [comment]
该S3M SDK主要是面向行标《空间三维模型瓦片数据格式》（对应S3M 3.01）的，如果是使用SuperMap iDesktopX和S3M SDK生成S3M 3.01数据，内部实现是完全一致的，均符合行标规定。截图提供的示例应该分别是S3M 3.01数据（左）和S3M 3.0数据（右），所以它们存在些许细节差异。
