### ISSUE TITLE
s3m_sdk应该有比较严重的内存泄露

### ISSUE THREAD

**Issue by elfc2000** [SuperMap/s3m-spec#101]
sdk的源码里，到处都是 new 和 delete，为何不用智能指针。
修改sample示例代码，做了一个简单测试，这一行调用足够多的次数，内存只增不降，这个sdk有对内存泄露的检查么
![微信截图_20241201004557](https://github.com/user-attachments/assets/7ecd41b6-3a01-4c8a-b283-6153d6b6b4d4)

**Comment by heqianhq** [comment]
已提交修改
