### ISSUE TITLE
S3M_Parser_JS 加载不支持desktop生成的三维缓存吗?

### ISSUE THREAD

**Issue by mhcxp** [SuperMap/s3m-spec#18]
加载后模型变形严重, 初始化时也无法定位到模型位置
![image](https://user-images.githubusercontent.com/3632301/111338910-497a8900-86b2-11eb-861b-1d84bef8fa1d.png)

**Comment by lishulincug** [comment]
遇到同样问题，怎么回事

**Comment by pasu** [comment]
你好，是否可以提供一个数据片段，我们分析一下具体的问题。谢谢

**Comment by pasu** [comment]
S3M_Parser_JS是基于S3M规范文档中对应的格式进行的读写解析，desktop生成的三维缓存提供了很多新的能力和属性，版本号不一定和S3M_Parser_JS支持的版本一致。后续我们也会跟进该问题，更好的支持S3M的版本，如有问题请进一步反馈，非常感谢。
