### ISSUE TITLE
发现内存泄漏的问题

### ISSUE THREAD

**Issue by Annie834** [SuperMap/s3m-spec#19]
SDK2019的例子：ImgToolkit::GetTextureData(texturePath)这个获取材质数据的时候会出现内存泄漏的问题。

**Comment by pasu** [comment]
你好，很抱歉这么晚答复。
请问，是否可以提供测试数据，我们自己的数据都正常，没有内存泄漏的问题。谢谢

**Comment by Annie834** [comment]
之前我用的模型有几百张图片测试发现这个函数会导致内存泄漏，后面去发帖问了改了一次，重新下载的版本内存泄漏就少了很多
TextureData* ROGroupLite::CreateTextureData(wstring texturePath)
{
	TextureData* m_pTextureData = ImgToolkit::GetTextureData(texturePath, true);
	return m_pTextureData;
}



PS：关于LOD层级的事情是，我用gltf转UDB用idesktop打开再缓存成S3M切片的时候是有LOD层级的，但是你上一个邮件中回复中却说只是针对单个切片，gltf没有LOD的概念那就转换不了带LOD 的S3MB的了吗


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SuperMap/s3m-spec"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月14日(星期五) 上午10:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [SuperMap/s3m-spec] 发现内存泄漏的问题 (#19)





 
你好，很抱歉这么晚答复。
 请问，是否可以提供测试数据，我们自己的数据都正常，没有内存泄漏的问题。谢谢

**Comment by pasu** [comment]
1 内存泄漏问题如果满足要求，是否可以关闭该issue？默认关闭，如果觉得不满足要求，可以开启并提供测试数据，谢谢。
2 gltf没有LOD概念，但在桌面中生成缓存时，增加了LOD的概念。gltf属于单个模型，可以认为对应的是精细层的S3MB切片。没有LOD的gltf可以认为只有一层LOD的数据，你在桌面生成时仅指定一层LOD就可以转成对应的S3MB了。
