### ISSUE TITLE
S3M_Parser_JS加载isever 10i发布的倾斜摄影s3mb会报缺少顶点数据的错误

### ISSUE THREAD

**Issue by Noah-Gilga** [SuperMap/s3m-spec#21]
源数据在桌面端是可以正常显示的，S3M_Parser_JS加载会报以下错误
![image](https://user-images.githubusercontent.com/42824389/118229172-20158800-b4be-11eb-8df2-36b6f4df5114.png)
并且会出现以下的效果，在桌面端是不会的
![image](https://user-images.githubusercontent.com/42824389/118229219-36bbdf00-b4be-11eb-9566-892024b0b762.png)
数据有点大，我可以之后上传

**Comment by pasu** [comment]
你好，大概率是你的S3MB数据是最新的版本，而开源的S3M_Parser_JS并不支持最新版的S3MB，两者格式不一致导致的。
请提供一个切片的数据，应该就可以，我们这边确认一下，谢谢。

**Comment by Noah-Gilga** [comment]
> 请提供一个切片的数据，应该就可以，我们这边确认一下，谢谢。
------------------------------------------------------------------------------------
好的，我把这两份数据的两个切片数据上传了。
链接：https://pan.baidu.com/s/1KLFTVZ4ed68ddpdVKaE6qQ 
提取码：bmri 
复制这段内容后打开百度网盘手机App，操作更方便哦

**Comment by pasu** [comment]
收到，我们下载下来看看，辛苦

**Comment by pasu** [comment]
你好，提供的切片数据是可以正常浏览的，代码请看附件，效果如下：
![Uploading 倾斜截图.png…]()

**Comment by Noah-Gilga** [comment]
> 你好，提供的切片数据是可以正常浏览的，代码请看附件，效果如下：
> 
> ![倾斜截图](https://user-images.githubusercontent.com/2180609/119305851-dd149b00-bc9b-11eb-842a-6a4678ff1fee.png)
> 
> [code.zip](https://github.com/SuperMap/s3m-spec/files/6530242/code.zip)

你好，谢谢回答，附件中的代码我也能成功加载了。另外我想请问一下，附件里面的scp和我由超图桌面端生成并发布的scp的参数有少许的不同，不知道问题是否因为这些属性参数引起的呢，几个属性的区别如下：
附件中的.scp                                                                       我本地超图桌面端生成并发布的的.scp
"dataType":"ObliquePhotogrammetry"                               "dataType":"BIM"
"s3m:FileType":"OSGBFile"                                                   "s3m:FileType":"OSGBCacheFile",
"s3m:RenderMode":"Normal",                                             "s3m:TextureSharing":"FALSE",
"s3m:TileSplitType":"LOCAL",                                               "s3m:TileSplitType":"GLOBAL",
                                                                                             "s3m:VertexWeightMode":"DatasetField",

**Comment by Noah-Gilga** [comment]
> 你好，提供的切片数据是可以正常浏览的，代码请看附件，效果如下：
> 
> ![倾斜截图](https://user-images.githubusercontent.com/2180609/119305851-dd149b00-bc9b-11eb-842a-6a4678ff1fee.png)
> 
> [code.zip](https://github.com/SuperMap/s3m-spec/files/6530242/code.zip)

你好，谢谢回答，附件中的代码我也能成功加载了。另外我想请问一下，附件里面的scp和我由超图桌面端生成并发布的scp的参数有少许的不同，不知道问题是否因为这些属性参数引起的呢，几个属性的区别如下：
附件中的.scp                                                                       我本地超图桌面端生成并发布的的.scp
"dataType":"ObliquePhotogrammetry"                               "dataType":"BIM"
"s3m:FileType":"OSGBFile"                                                   "s3m:FileType":"OSGBCacheFile",
"s3m:RenderMode":"Normal",                                             "s3m:TextureSharing":"FALSE",
"s3m:TileSplitType":"LOCAL",                                               "s3m:TileSplitType":"GLOBAL",
                                                                                             "s3m:VertexWeightMode":"DatasetField",

**Comment by pasu** [comment]
我们也是由桌面生成的，你是否可以对比的替换一下scp，看看是哪个参数导致的？我们这边也会抽时间对比一下。
重点的参数是：**"dataType":"ObliquePhotogrammetry"** **"s3m:FileType":"OSGBFile"**,"s3m:RenderMode":"Normal",**"s3m:TileSplitType":"LOCAL"**

**Comment by pasu** [comment]
麻烦你也提供一下你的scp，我们可以对比一下，谢谢。 @Noah-Gilga

**Comment by Noah-Gilga** [comment]
> 麻烦你也提供一下你的scp，我们可以对比一下，谢谢。 @Noah-Gilga


这个是我这边超图生成的scp[localScp.txt](https://github.com/SuperMap/s3m-spec/files/6537082/localScp.txt)，我把里面的重点参数替换了也还是会出现顶点着色器报错的问题，我跟代码是会发现在S3MCacheFileRenderEntity.js里面执行：
this.vertexArray = new Cesium.VertexArray({
      context : context,
      attributes : attributes,
      indexBuffer : indexPackage.indexBuffer
  });
里面的attributes元素会出现既没有value也没有vertexBuffer的错误，然后就会引起顶点着色器报错

![image](https://user-images.githubusercontent.com/42824389/119451842-4bbf2a80-bd68-11eb-96ac-089ebaeb29db.png)

**Comment by pasu** [comment]
应该还是某一个S3M数据导致的问题，但不是你提供的那两个数据。我们这边也找一下新版本的数据看一下，如果你能找到对应出错的S3M数据，也麻烦提供给我们该数据切片，谢谢

**Comment by pasu** [comment]
对了，你说这个数据是iserver10i的数据？是哪一个示例数据，你说一下数据名字，iserver的数据我们自己也都有的

**Comment by Noah-Gilga** [comment]
好的我尝试找一下出错的数据，这个数据是用iserver10i生成并发布的数据，不是示例数据，是我自己做的

**Comment by pasu** [comment]
请问，是否找到对应出错数据，或者提供一个能重现该问题的数据？谢谢

**Comment by Noah-Gilga** [comment]
因为数据太大，现在目前还找不到对应出错的数据，还在努力尝试找

**Comment by pasu** [comment]
兄弟，我先关闭该缺陷了，后续你提供重现数据再开启该问题，这样可以不
