### ISSUE TITLE
有没有使用S3M_Parser_JS（S3M_Parser_JS是用于S3MB数据在Web端的解析及加载的库）示例？

### ISSUE THREAD

**Issue by shanshan1405** [SuperMap/s3m-spec#23]
使用方法
1. 在Cesium官网下载release包，将包里的Build文件夹放在根目录(ReadMe文件上一级)
2. 准备数据，并在服务端（比如tomcat）发布
3. 运行helloworld.html

没看懂。有没有使用S3M_Parser_JS（S3M_Parser_JS是用于S3MB数据在Web端的解析及加载的库）示例？

**Comment by pasu** [comment]
针对你提到的问题，对说明部分进行了适当修改
