### ISSUE TITLE
是否提供加载supermap iserver发布的s3m服务的代码？

### ISSUE THREAD

**Issue by wzwxwc** [SuperMap/s3m-spec#26]
你好，我用原生Cesium.js开发了一套公司内部的sdk
现在想支持超图的s3m服务
例如
http://www.supermapol.com/realspace/services/3D-CBDbuilding/rest/realspace
请问咱们是否提供加载s3m服务的相关开源js插件
可以和原生Cesium.js集成
谢谢

**Comment by pasu** [comment]
近期会提供，具体内容暂不方便透漏。
