### ISSUE TITLE
原生Cesium添加S3M模型后怎么实现这个模型的移动旋转缩放功能呢

### ISSUE THREAD

**Issue by YourSword** [SuperMap/s3m-spec#27]
我尝试在添加到原生Cesium里后，修改layer的modelMatrix参数，或者_position或者rectangle参数，发现模型位置并没有被改变，请问我该怎么去操作layer去实现这个功能呢？

**Comment by pasu** [comment]
你可以看一下这段代码：https://github.com/SuperMap/s3m-spec/blob/master/S3M_SDK/S3M_Parser_JS/js/S3MTiles/S3MTilesLayer.js#L88
该矩阵相当于是该模型的锚点，你可以更新该矩阵来实现对应的功能，这个矩阵会应用于整个图层。

**Comment by lishulincug** [comment]
链接打不开

**Comment by pasu** [comment]
[function parseGeodes(layer, content, materialTable, pagelodNode, pagelod) {](https://github.com/SuperMap/s3m-spec/blob/8f1d896016e76e6cc0fa6bda5eef16078320c55d/S3M_SDK/S3M_JS/S3M_module/S3MTiles/S3MContentParser.js#L134)
