### ISSUE TITLE
加载倾斜摄影数据出错

### ISSUE THREAD

**Issue by lzc1718** [SuperMap/s3m-spec#28]
在S3ModelParser.js的S3ModelParser.parseBuffer获取到nOptions为0。
在parsePickInfo函数不满足if((nOptions & 1) === 1)条件，直接跳出处理。最终导致pickInfo为空而没加载到数据。

![image](https://user-images.githubusercontent.com/39751466/126607558-d9ae17c1-8c0c-4709-8c34-8fe3ff26d472.png)

![image](https://user-images.githubusercontent.com/39751466/126607627-9070c222-7635-4690-bf12-e1b9e7c3f81b.png)

**Comment by pasu** [comment]
请提供一个切片数据，谢谢

**Comment by pasu** [comment]
没有反馈，关闭
