### ISSUE TITLE
加载s3mb格式单体化模型数据，有请求，但是模型没有加载出来

### ISSUE THREAD

**Issue by xianshangdeyu** [SuperMap/s3m-spec#29]
加载s3mb格式单体化模型数据，有请求，但是模型没有加载出来

**Comment by xianshangdeyu** [comment]
我们用超图软件转换出来的数据比你们的data中的数据多了一个.s3md后缀的文件，请问是什么问题导致数据加载了但是显示

**Comment by pasu** [comment]
1 问题描述比较少，不太容易定位。2 在最新的规范中支持数据的属性内容，以s3md的形式提供。
