### ISSUE TITLE
加载s3mb模型效果不佳

### ISSUE THREAD

**Issue by liyanfu520** [SuperMap/s3m-spec#30]
一、步骤
1、3dmax导出fbx格式的三维模型
2、超图桌面版10i导入fbx模型
![8](https://user-images.githubusercontent.com/40288288/131650113-59280e80-6560-4c94-879e-4222bc5e6d7f.png)

3、超图桌面版10i进行转换成S3MB格式
如果顶点优化方式选择不压缩，大小是正常的
![6](https://user-images.githubusercontent.com/40288288/131649811-279b11d4-0000-4645-b1ea-06b4c4c9def9.png)
![9](https://user-images.githubusercontent.com/40288288/131650648-c5bb464d-3b0e-432a-a762-c84331cefd0a.png)

如果顶点优化方式选择压缩，大小是不正常的
![10](https://user-images.githubusercontent.com/40288288/131650792-e1d75ef5-3005-4314-ba56-74c3b9f9ff52.png)

4、通过CBD.html示例程序进行修改后加载，模型可以加载出来
5、通过IIS发布，查看加载效果

二、问题
1、不知道我的操作步骤能否改进
2、加载的效果质量不佳，模型和纹理都有问题，如何解决
3、想知道示例数据中的CBD是怎么转出来的，我也想通过这种转换方式试试
下面是两种效果对比
超图桌面版10i加载效果
![3](https://user-images.githubusercontent.com/40288288/131644779-b7e79e1c-1e97-4b15-bd37-1ddc6988b9bf.png)
![4](https://user-images.githubusercontent.com/40288288/131644785-ca455be6-e9bc-4bbd-9ec8-b1a10d8ac369.png)

CBD.html加载效果
![1](https://user-images.githubusercontent.com/40288288/131644841-c6c95eb1-8da4-4d15-9f25-547fd5ffa76f.png)
![2](https://user-images.githubusercontent.com/40288288/131644849-981013aa-d7ca-4ab7-9400-37f90c33d82b.png)

三、测试数据和Cesium包
fbx格式数据
链接：https://pan.baidu.com/s/1xhPdTklAfFYw2boH61eITA 
提取码：1111

转完s3mb格式数据
链接：https://pan.baidu.com/s/1NZfq5AB45b-zP-3VdIqZmw 
提取码：1111

build包
链接：https://pan.baidu.com/s/1glgxLoEVIpctSSlzBqQSYA 
提取码：1111

Cesium版本
![5](https://user-images.githubusercontent.com/40288288/131645786-b10ce647-e3de-428f-9f89-91b569de8821.png)

修改后CBD.html

`
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport"
    content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1, user-scalable=no">
  <title>CBD</title>
  <link href="../Build/Cesium/Widgets/widgets.css" rel="stylesheet">
  <script src="../Build/Cesium/Cesium.js"></script>
  <script src="./js/require.min.js"></script>
  <style>
    html,
    body,
    #cesiumContainer {
      width: 100%;
      height: 100%;
      margin: 0;
      padding: 0;
      overflow: hidden;
    }
  </style>
</head>

<body>
  <div id="cesiumContainer">
  </div>
  <script>
    let viewer = new Cesium.Viewer('cesiumContainer', {
    });
    let scene = viewer.scene;
    require(['./js/S3MTiles/S3MTilesLayer'], function (S3MTilesLayer) {
      let layer = new S3MTilesLayer({
        context: scene._context,
        url: './data/L1/L1.scp'
        // url: './data/CBD/cbd.scp'
      });

      scene.primitives.add(layer);

      layer.readyPromise.then(function () {
        var boundingSphere = Cesium.BoundingSphere.fromRectangle2D(layer.rectangle);
        boundingSphere.center = layer.position;

        scene.camera.viewBoundingSphere(boundingSphere, new Cesium.HeadingPitchRange(0.0, -0.5, boundingSphere.radius));
        scene.camera.lookAtTransform(Cesium.Matrix4.IDENTITY);
      }).otherwise(function (error) {
        console.log(error);
      });

      // layer.readyPromise.then(function () {
      //   scene.camera.setView({
      //     destination: new Cesium.Cartesian3(-2181968.890329965, 4385313.17843029, 4072712.8241634783),
      //     orientation: {
      //       heading: 3.1756648661534443,
      //       pitch: -0.3715184468182904
      //     }
      //   });
      // }).otherwise(function (error) {
      //   console.log(error);
      // });
    })
  </script>
</body>

</html>`

可以直接运行的完整包，test3.html是入口
链接：https://pan.baidu.com/s/1VEl1WEII3ADZJJjyvQx6sg 
提取码：1111

**Comment by pasu** [comment]
请问，如果顶点优化方式选择不压缩，效果正常吗？

**Comment by liyanfu520** [comment]
大小正常，效果不正常，上面有截图，CBD.html加载效果就是顶点优化方式选择不压缩的效果

**Comment by liyanfu520** [comment]
刚测试了大一点的数据，初看上去效果还行，但是因为报错，看不全
报错截图
![1](https://user-images.githubusercontent.com/40288288/131822365-f95fedb1-49ed-4192-a959-c64b71dbe2df.png)
![2](https://user-images.githubusercontent.com/40288288/131822370-70e17381-f75a-4c56-94ea-9f250822c84d.png)

测试数据
链接：https://pan.baidu.com/s/1hAEITuCwS80chK9ptxec5w 
提取码：1111

**Comment by pasu** [comment]
收到，这边先重现一下

**Comment by supermap123** [comment]
已解决

**Comment by liyanfu520** [comment]
解决问题了吗？？为什么我刚下载测试之后问题还是有呢？？

**Comment by liyanfu520** [comment]
![4](https://user-images.githubusercontent.com/40288288/134460936-01c9c7f6-9b06-4dbc-b206-a848be1fb7db.png)
![2](https://user-images.githubusercontent.com/40288288/134460940-4921db5a-6d1b-4a34-9bc2-2d5ce4b2ed3b.png)
![3](https://user-images.githubusercontent.com/40288288/134460946-07601a3e-bd08-4d32-a660-ca37ce54f90c.png)

**Comment by liyanfu520** [comment]
用CBD.html也是报错
![5](https://user-images.githubusercontent.com/40288288/134462319-f0a4cbf3-2974-4439-b86e-134b0c3f08b9.png)

**Comment by liyanfu520** [comment]
![5](https://user-images.githubusercontent.com/40288288/134462357-bd6133a0-3746-4592-a274-d1015c59d43c.png)

**Comment by supermap123** [comment]
少提交了着色器东西，刚提交了

**Comment by supermap123** [comment]
此插件开源只提供了解析S3M部分，若只考虑使用，建议使用未开源源码S3M完整插件
https://github.com/SuperMap/iClient3D-for-WebGL/tree/main/Cesium_S3MLayer_Plugins/S3MTilesLayer

**Comment by liyanfu520** [comment]
测试数据L1这个是可以正常浏览，但是效果不好，还有一个测试数据初看效果还可以，但是会报错，之前其实也有提供，好像过期了，现在重新提供
链接：https://pan.baidu.com/s/1UVskeP4wWU_3naboYuuA3Q 
提取码：1111
