### ISSUE TITLE
有linux版本的吗

### ISSUE THREAD

**Issue by stevechaw** [SuperMap/s3m-spec#31]
我在用ubuntu16.04, 请问有在linux上的版本吗?

**Comment by stevechaw** [comment]
我想把obj文件转换到s3mb格式

**Comment by pasu** [comment]
目前暂未提供linux版本，内部已经做为需求，正在实现中

**Comment by stevechaw** [comment]
> 目前暂未提供linux版本，内部已经做为需求，正在实现中

您好, 请问能否给我一个简单的demo, 只需要把obj转换到s3mb, 不需要其他的操作. 我看文档里s3m文件结构还比较复杂, 自己实现比较困难. 方便的话可以给一份吗? 万分感谢!

**Comment by pasu** [comment]
目前不支持obj，我们支持的是osgb或3dtiles转为s3mb格式，你需要先将obj格式转为上述两种格式中的一种。

**Comment by stevechaw** [comment]
> 目前不支持obj，我们支持的是osgb或3dtiles转为s3mb格式，你需要先将obj格式转为上述两种格式中的一种。

把obj转为osgb这个没问题

**Comment by stevechaw** [comment]
可否提供一个小demo, 把osgb转成s3mb. 你们sdk里的库在linux环境下无法使用, 有蛮多接口用不了的.
