### ISSUE TITLE
S3M_JS 加载不了 idesktop10i 转换的 s3m，加载不报错，但是看不到模型

### ISSUE THREAD

**Issue by sunvictor** [SuperMap/s3m-spec#32]
S3M_JS 加载不了 idesktop10i 转换的 s3m，加载不报错，但是看不到模型

**Comment by pasu** [comment]
请提供问题数据

**Comment by sunvictor** [comment]
> 请提供问题数据

链接：https://pan.baidu.com/s/1RQ8togrLX_l75MoCCHjDMg 
提取码：9n91

**Comment by pasu** [comment]
目前暂未支持，近期提供，请保证链接有效，方便我们测试，谢谢

**Comment by zhongshuiyuan** [comment]
是的，加载不了，也没有任何错误

**Comment by zhongshuiyuan** [comment]
http://cust10.jointsurvey.com:8888/Joint3dService/XiNan/ace1f66f6bf648f0899e1caa07f3d53f/

这个是我的数据，用老版本可以，但升级到新版本时不行了
![image](https://user-images.githubusercontent.com/8955999/143848305-9ed67772-29be-450f-ab08-e9fd8cda532d.png)

我看了下，有网络请求，但是就是显示不了
![image](https://user-images.githubusercontent.com/8955999/143848800-0e1ea2aa-bcdc-46b3-b820-7ba887aef5c5.png)

**Comment by haoran1012** [comment]
> http://cust10.jointsurvey.com:8888/Joint3dService/XiNan/ace1f66f6bf648f0899e1caa07f3d53f/
> 
> 这个是我的数据，用老版本可以，但升级到新版本时不行了 ![image](https://user-images.githubusercontent.com/8955999/143848305-9ed67772-29be-450f-ab08-e9fd8cda532d.png)
> 
> 我看了下，有网络请求，但是就是显示不了 ![image](https://user-images.githubusercontent.com/8955999/143848800-0e1ea2aa-bcdc-46b3-b820-7ba887aef5c5.png)

遇到同样问题，请问你说的老版本是指什么？sdk的老版本？还是idesktop的老版本？

**Comment by zhongshuiyuan** [comment]
指的是sdk
新版S3M JS 加载不了 idesktop10i 转换的 s3mb，加载不报错，但是看不到模型
老版本的S3M JS 可以加载idesktop10i 转换的 s3mb

我们的数据大部分是基于idesktop10i转的，这几天看到js sdk有更新，也想跟着更新，但是加载不出数据。

**Comment by zhongshuiyuan** [comment]
指的是sdk
新版S3M JS 加载不了 idesktop10i 转换的 s3mb，加载不报错，但是看不到模型
老版本的S3M JS 可以加载idesktop10i 转换的 s3mb

我们的数据大部分是基于idesktop10i转的，这几天看到js sdk有更新，也想跟着更新，但是加载不出数据。

> > http://cust10.jointsurvey.com:8888/Joint3dService/XiNan/ace1f66f6bf648f0899e1caa07f3d53f/
> > 这个是我的数据，用老版本可以，但升级到新版本时不行了 ![image](https://user-images.githubusercontent.com/8955999/143848305-9ed67772-29be-450f-ab08-e9fd8cda532d.png)
> > 我看了下，有网络请求，但是就是显示不了 ![image](https://user-images.githubusercontent.com/8955999/143848800-0e1ea2aa-bcdc-46b3-b820-7ba887aef5c5.png)
> 
> 遇到同样问题，请问你说的老版本是指什么？sdk的老版本？还是idesktop的老版本？

指的是sdk
新版S3M JS 加载不了 idesktop10i 转换的 s3mb，加载不报错，但是看不到模型
老版本的S3M JS 可以加载idesktop10i 转换的 s3mb

我们的数据大部分是基于idesktop10i转的，这几天看到js sdk有更新，也想跟着更新，但是加载不出数据。

**Comment by haoran1012** [comment]
> 指的是sdk 新版S3M JS 加载不了 idesktop10i 转换的 s3mb，加载不报错，但是看不到模型 老版本的S3M JS 可以加载idesktop10i 转换的 s3mb
> 
> 我们的数据大部分是基于idesktop10i转的，这几天看到js sdk有更新，也想跟着更新，但是加载不出数据。
> 
> > > http://cust10.jointsurvey.com:8888/Joint3dService/XiNan/ace1f66f6bf648f0899e1caa07f3d53f/
> > > 这个是我的数据，用老版本可以，但升级到新版本时不行了 ![image](https://user-images.githubusercontent.com/8955999/143848305-9ed67772-29be-450f-ab08-e9fd8cda532d.png)
> > > 我看了下，有网络请求，但是就是显示不了 ![image](https://user-images.githubusercontent.com/8955999/143848800-0e1ea2aa-bcdc-46b3-b820-7ba887aef5c5.png)
> > 
> > 
> > 遇到同样问题，请问你说的老版本是指什么？sdk的老版本？还是idesktop的老版本？
> 
> 指的是sdk 新版S3M JS 加载不了 idesktop10i 转换的 s3mb，加载不报错，但是看不到模型 老版本的S3M JS 可以加载idesktop10i 转换的 s3mb
> 
> 我们的数据大部分是基于idesktop10i转的，这几天看到js sdk有更新，也想跟着更新，但是加载不出数据。

能发一份老版的sdk吗？809449959@qq.com  谢谢啦！

**Comment by zhongshuiyuan** [comment]
> > 指的是sdk 新版S3M JS 加载不了 idesktop10i 转换的 s3mb，加载不报错，但是看不到模型 老版本的S3M JS 可以加载idesktop10i 转换的 s3mb
> > 我们的数据大部分是基于idesktop10i转的，这几天看到js sdk有更新，也想跟着更新，但是加载不出数据。
> > > > http://cust10.jointsurvey.com:8888/Joint3dService/XiNan/ace1f66f6bf648f0899e1caa07f3d53f/
> > > > 这个是我的数据，用老版本可以，但升级到新版本时不行了 ![image](https://user-images.githubusercontent.com/8955999/143848305-9ed67772-29be-450f-ab08-e9fd8cda532d.png)
> > > > 我看了下，有网络请求，但是就是显示不了 ![image](https://user-images.githubusercontent.com/8955999/143848800-0e1ea2aa-bcdc-46b3-b820-7ba887aef5c5.png)
> > > 
> > > 
> > > 遇到同样问题，请问你说的老版本是指什么？sdk的老版本？还是idesktop的老版本？
> > 
> > 
> > 指的是sdk 新版S3M JS 加载不了 idesktop10i 转换的 s3mb，加载不报错，但是看不到模型 老版本的S3M JS 可以加载idesktop10i 转换的 s3mb
> > 我们的数据大部分是基于idesktop10i转的，这几天看到js sdk有更新，也想跟着更新，但是加载不出数据。
> 
> 能发一份老版的sdk吗？[809449959@qq.com](mailto:809449959@qq.com) 谢谢啦！

来，阿里云盘，有需要的来
「s3m-spec-master」，点击链接保存，或者复制本段内容，打开「阿里云盘」APP ，无需下载极速在线查看，视频原画倍速播放。链接：https://www.aliyundrive.com/s/C9R1Y3yHggV

**Comment by supermap123** [comment]
新版本没问题，请下载后使用
![image](https://user-images.githubusercontent.com/58579283/148006138-689d07ce-6fde-4f12-b4a0-884ab69d3812.png)
