### ISSUE TITLE
通过s3m数据读取sdk读取到的TextureData指针，有什么办法可以单独导出成指定格式(jpg/png)文件保存?

### ISSUE THREAD

**Issue by hisoka2201** [SuperMap/s3m-spec#33]
使用最新的S3MB_SDK，开发环境vs2015

通过s3m数据读取sdk读取到的TextureData指针，有什么办法可以将TextureData数据单独导出成指定格式(jpg/png)文件保存?

**Comment by pasu** [comment]
该功能在SDK中不支持。请使用超图桌面产品，流程如下：
- S3M导入数据集
- 三维地理---材质---导出材质
