### ISSUE TITLE
S3M转3D_Tiles，iEarth工具闪退，转换失败。

### ISSUE THREAD

**Issue by FakeGISer** [SuperMap/s3m-spec#35]
![image](https://user-images.githubusercontent.com/94105377/141263182-e5b1cb23-f0cc-48aa-bc67-210fe1ff3c7e.png)
RT

**Comment by pasu** [comment]
1 请提供出问题的S3M数据切片，一个就可以。
2 请提供一些必要的重现信息，比如是偶尔某个切片出错，还是所以切片都出错？长时间运行后才出现问题？数据量大概多少等信息。
谢谢。

**Comment by pasu** [comment]
没有反馈
