### ISSUE TITLE
空间数据格式中的instanceinfo 实例化信息

### ISSUE THREAD

**Issue by hust1023** [SuperMap/s3m-spec#36]
空间数据格式中的instanceinfo 实例化信息是什么用处呢，以及怎么生成数据呢
根据文档中给出的格式，结合s3m_js代码，结构体格式并没有对上,可以给解释一下吗

**Comment by pasu** [comment]
1 实例化信息用于实例化渲染，比如场景中的树，草，窗户等地物，模型相同，只是位置不同时，适合采用实例化渲染。
2 可以通过超图桌面生成S3M数据时，勾选实例化
3 具体解析可参考示例程序中提供的方法：https://github.com/SuperMap/s3m-spec/blob/6cda7fd4f537125906af344b18a3a2fb1b6840d5/S3M_SDK/S3M_JS/S3M_module/S3MParser/S3ModelParser.js#L330
