### ISSUE TITLE
s3mTileLayer设置颜色不起作用

### ISSUE THREAD

**Issue by lishulincug** [SuperMap/s3m-spec#37]
测试style3D不起效果，是什么问题
s3mTilesLayers[0].style3D.fillForeColor = new Cesium.Color(1,0,0,1);
15:07:03.879 Color {red: 1, green: 0, blue: 0, alpha: 1}

![image](https://user-images.githubusercontent.com/13003282/147444786-0db72803-ae15-4632-925a-bbaa55fdb8c0.png)

**Comment by supermap123** [comment]
新版没问题，请下载新版后使用
![image](https://user-images.githubusercontent.com/58579283/148003746-99cc5dc8-3972-44fe-928d-9903c691376e.png)

**Comment by lishulincug** [comment]
本人使用的是https://github.com/SuperMap/iClient3D-for-WebGL 这个插件的S3MTilesLayer加载的，这个加载时设置颜色时不起效。
![image](https://user-images.githubusercontent.com/13003282/148006771-cd17c78a-e8d0-4c9b-9477-0c4176253935.png)

**Comment by pasu** [comment]
后续会在TilesLayer同步这个功能

**Comment by supermap123** [comment]
新版已解决，请下载后使用
