### ISSUE TITLE
s3m 转换的 b3dm 与 ModelExperimental 冲突

### ISSUE THREAD

**Issue by Sglight** [SuperMap/s3m-spec#38]
使用转换工具将 idesktop 生成的 S3M 模型转换为 b3dm 后，使用 Cesium 1.89 加载，与 ModelExperimental 冲突，不使用 ModelExperimental 则正常加载。

![image](https://user-images.githubusercontent.com/29850632/149857778-979fabe9-9217-4fa2-9d2f-6e5438be40de.png)

**Comment by pasu** [comment]
ModelExperimental 是什么？

**Comment by Sglight** [comment]
> ModelExperimental 是什么？

https://cesium.com/blog/2021/12/01/cesium-releases-in-december-2021/

新的加载模型方式，支持自定义着色器
