### ISSUE TITLE
转换工具的问题

### ISSUE THREAD

**Issue by skylning** [SuperMap/s3m-spec#4]
转换工具怎么所有带转换文件都需要scp文件？例如dae也是让选择scp文件，osgb也是让选择scp文件？

**Comment by oneKonw** [comment]
请问你的S3M->3Dtiles功能转换出来的3Dtiles文件有出现纹理丢失的情况吗？

**Comment by skylning** [comment]
没有用，绑定超图软件的话感觉意义就不大了

**Comment by skylning** [comment]
除非有跟其他工具存在大不同或者优势，对个人开发者来说,cesiumlab就是免费的，即使收费也才2万

**Comment by pasu** [comment]
采用SCP的好处是可以获取数据的根节点和基本信息（地理范围等），支持多文件的转换。SCP在超图桌面产品中可以自动创建，
也支持数据转换，均免费提供。
S3M本身是一种开放的数据规范，免费提供相关的数据转换工具。
