### ISSUE TITLE
请问s3mb中的顶点坐标是不是应该ENU坐标系下的坐标

### ISSUE THREAD

**Issue by shuguohui** [SuperMap/s3m-spec#48]
常见的倾斜摄影osgb数据，有一个metadata.xml以及Data目录，请问倾斜osgb转s3mb过程中，是不是把metadata.xml中的<SRSOrigin>中的xyz偏移量转换到WGS84下，作为scp文件中：
 "position" : {
      "units" : "Degree",
      "x" : 
      "y" : 
      "z" :
   },
这部分的值，然后每个tile目录中的数据，以这个position为原点建立ENU坐标系，然后osgb中的数据都转到这个ENU坐标系下？

**Comment by supermapliukaiyun** [comment]
是的
