### ISSUE TITLE
转换工具问题

### ISSUE THREAD

**Issue by oneKonw** [SuperMap/s3m-spec#5]
转换工具中的S3M->3Dtiles功能转换后文件出现纹理丢失，多个测试文件都出现这个情况，请问能提供测试文件测试一下是不是我这边的文件出问题了吗？

**Comment by pasu** [comment]
你好，如下是萨尔茨堡的在线数据，请查看，谢谢。
http://www.supermapol.com/realspace/services/3D-srsb/rest/realspace/datas/srsb
