### ISSUE TITLE
cesium1.91删除了原来的cesium.when,使用了promise,会报错

### ISSUE THREAD

**Issue by Mrzhubingxin** [SuperMap/s3m-spec#54]
![183790166-e5c47961-c081-4eb3-aea3-ca6a966b2edc](https://user-images.githubusercontent.com/92559206/183791101-57eed982-1fad-4a11-8a28-ef24fae8d487.png)

**Comment by Mrzhubingxin** [comment]
![183790267-c9ec9137-8f34-48c6-b45a-e08d6985486f](https://user-images.githubusercontent.com/92559206/183791135-94070af5-76f5-4cc3-a046-5a841f08f83f.png)
改完所有的之后cbd可以加载

**Comment by Mrzhubingxin** [comment]
![183790378-d77ee325-ef0c-40ce-bdcd-a6c07817f6f6](https://user-images.githubusercontent.com/92559206/183791172-4d597e96-fd8f-4258-9fe3-c68e230fff1c.png)
instance只加载了一块且报
![183790461-0fcd8cd0-6b59-4ac8-b46f-4d79307db64a](https://user-images.githubusercontent.com/92559206/183791183-4e3185df-7d62-48bf-8ef1-137cdf5ee8ce.png)
错

**Comment by supermapliukaiyun** [comment]
该问题已修复，请下载最新源码进行使用。

**Comment by Mrzhubingxin** [comment]
[image: 1661409543474.png]这里没改啊，我从哪里拉取最新的代码

liukaiyun ***@***.***> 于2022年8月25日周四 13:47写道：

**Comment by Mrzhubingxin** [comment]
![image](https://user-images.githubusercontent.com/92559206/186593579-d9cb2267-b11a-4bc2-84ea-ac5c9fbc5249.png)
我刚拉的，这也没改啊
