### ISSUE TITLE
S3M 2.0 3.0说明文档

### ISSUE THREAD

**Issue by lntseu** [SuperMap/s3m-spec#55]
您好。

S3M格式经过几年的更新，现在已经来到3.0版本，但是此处开源的文档仍然是面向1.0的，过于陈旧。

请问是否可以开放S3M 2.0和3.0的文明文档。

另外，是否可以开放读写高版本S3M格式中的.attribute文件的C++ SDK。

**Comment by pasu** [comment]
你好，很抱歉给你的工作带来困扰。
目前，3.0的规范还在流程中，存在变更的可能，属于小范围试用阶段，并不适合公开该规范，所以暂不对外开放，请理解。
SDK已经作为需求，还在规划中，我们会推动这个工作，提供属性信息的C++读写能力：https://github.com/SuperMap/s3m-spec/issues/34。
如果你对3.0规范有任何明确的建议，欢迎交流。
