### ISSUE TITLE
依旧不支持1.91以上的cesium加载s3m，并且修改完报错到指定位置还是不显示

### ISSUE THREAD

**Issue by GGBond-GIS** [SuperMap/s3m-spec#56]
![1661412903942](https://user-images.githubusercontent.com/92559206/186603916-5827cbbe-2906-4249-a414-e1fd8d466179.png)
这是我用3dtile
![1661412943157](https://user-images.githubusercontent.com/92559206/186604037-4c9fe09b-dbe9-4705-9bb1-3fdaa0ca5d84.png)
这是加载的s3m，什么也不显示
![image](https://user-images.githubusercontent.com/92559206/186604325-a0ced935-391a-455b-84bb-4c0a3ad230f3.png)
而且无不报错信息

**Comment by Mrzhubingxin** [comment]
我的上一个问题被关闭，说是已经修改，但是在我刚拉的代码中还是用了Cesium.when.defer();

**Comment by heqianhq** [comment]
已修改
