### ISSUE TITLE
cesium 利用S3MTilesLayer加载模型，浏览时有点卡顿

### ISSUE THREAD

**Issue by super3s1988** [SuperMap/s3m-spec#57]
cesium 利用S3MTilesLayer加载模型，浏览时有点卡顿，但是用超图的前端加载比较流畅，怎么解决呢

**Comment by pasu** [comment]
超图前端做了大量性能优化，可能涉及到数据或调度部分的优化，没有统一的解决方案。
而在Cesium中无法直接渲染S3M，需要实时转化，因此也会增大计算量
