### ISSUE TITLE
文档关于s3mb二进制流描述的部分有错误

### ISSUE THREAD

**Issue by FlyingCubicstone** [SuperMap/s3m-spec#59]
1.0标准实际上并没有unzippedSize的无符号4字节，如果按照unzippedSize存在的结构去解析二进制s3mb会发现后边的数据压缩包无法解压，会报缺失头的zlib error -3的错误

**Comment by heqianhq** [comment]
修改了文档的描述错误，已重新上传标准文档。

**Comment by FlyingCubicstone** [comment]
> 修改了文档的描述错误，已重新上传标准文档。

除了更新了这部分的内容，还有其他地方有修改吗？新文档是在官网上吗？

**Comment by heqianhq** [comment]
你好：
新文档在仓库的specification文件夹内，除了属性数据文件的二进制流描述外，还修改了一些笔误，请知悉。



***@***.***
 
发件人： WilliamClarkson
发送时间： 2023-02-17 09:31
收件人： SuperMap/s3m-spec
抄送： heqianhq; State change
主题： Re: [SuperMap/s3m-spec] 文档关于s3mb二进制流描述的部分有错误 (Issue #59)
修改了文档的描述错误，已重新上传标准文档。
除了更新了这部分的内容，还有其他地方有修改吗？新文档是在官网上吗？
―
