### ISSUE TITLE
转换工具无法正常运行，找不到SuElement

### ISSUE THREAD

**Issue by xbq** [SuperMap/s3m-spec#6]
报错：由于找不到SuElement.dll,无法继续执行代码。重新安装程序可能会解决此问题
转换工具就是路径s3m-spec-master\ConversionTool\SuperMap_Data_Convert\SuperMap_Data_Convert的工具，排除了文件下载不完整的可能性，git上确实没有该文件

**Comment by pasu** [comment]
你好，目前提供的是IEarth_Qt，在我这可以正常打开。
