### ISSUE TITLE
s3mb文件解析出现错误

### ISSUE THREAD

**Issue by FlyingCubicstone** [SuperMap/s3m-spec#60]
http://ask.supermap.com/118715

**Comment by pasu** [comment]
是否可以提供对应数据？

**Comment by FlyingCubicstone** [comment]
[cube1.zip](https://github.com/SuperMap/s3m-spec/files/10357196/cube1.zip)

**Comment by FlyingCubicstone** [comment]
> 是否可以提供对应数据？
https://github.com/SuperMap/s3m-spec/files/10357196/cube1.zip
你好，数据已提供。是规范文档与数据文件不对应吗？

**Comment by pasu** [comment]
研发人员正在确认，有进展后会在这回复

**Comment by heqianhq** [comment]
已修改文本描述
