### ISSUE TITLE
请问怎么获取s3mb文件里的解压缩之后的纹理数据？

### ISSUE THREAD

**Issue by troublegirl1003** [SuperMap/s3m-spec#61]
m_pBuffer里面好像存储的是压缩之后的数据，想通过ImageOperator.h里面的Decode来得到解压缩之后的数据，但貌似用法不太对，大佬能不能指导一下这个Decode的用法，如果能给个例子最好了，感谢

**Comment by muyan520** [comment]
铁子，你会了吗

**Comment by troublegirl1003** [comment]
不会。。

**Comment by heqianhq** [comment]
可以直接调用ProcessTextureData()，将CodecType设置为encNONE, 但目前SDK只支持解压缩enrS3TCDXTN格式（即DXT格式）的数据。
