### ISSUE TITLE
使用S3M的SDK包解析s3mb文件的纹理信息失败

### ISSUE THREAD

**Issue by muyan520** [SuperMap/s3m-spec#62]
使用接口S3MB::ImageOperator::GetMipMapData()会崩溃 
使用S3MB::ImageOperator::Decode()得到的纹理颜色内存块不对

示例代码：
	S3MBReader S3MBReaderRo;

	wstring S3MBFileSrc = L"C:\\Users\\\liangqinlong\\Desktop\\s3mb\\data\\Tile_+023_+007\\Tile_+023_+007.s3mb";
	S3MBReaderRo.SetFilePath(S3MBFileSrc);
	S3MBReaderRo.ReadS3MBAsROGroup();
	RenderOperationGroup* Group = S3MBReaderRo.GetRenderOperationGroup();
	int num = Group->GetNumChildren();
	for (int i = 0; i < num; i++)
	{
		RenderOperationNode* pChild = Group;
		std::map<wstring, S3MB::Material*>& mats = pChild->GetMaterials();
		for (auto it = mats.begin(); it != mats.end(); ++it)
		{
			S3MB::Material* curmat = (it)->second;
			for (auto ittech = curmat->mTechniques.begin(); ittech != curmat->mTechniques.end(); ++ittech)
			{
				S3MB::Technique* temp = (*ittech);
				for (auto itpass = temp->mPasses.begin(); itpass != temp->mPasses.end(); ++itpass)
				{
					S3MB::Pass* pPass = *itpass;
					for (auto ittexu = pPass->m_pTextureUnitStates.begin(); ittexu != pPass->m_pTextureUnitStates.end(); ++ittexu)
					{
						S3MB::TextureDataInfo* ptexdatainfo = pChild->GetTextureData((*ittexu)->m_strTextureName);
						if (ptexdatainfo)
						{
							S3MB::TextureData* texdata = ptexdatainfo->m_pTextureData;
							//texdata->CompressTypeDXTToNONE();
							unsigned char* ppBufferOut = nullptr;
							std::vector<unsigned int> vecs;
							//int sss = S3MB::ImageOperator::GetMipMapData(texdata->m_nWidth, texdata->m_nHeight, texdata->m_pBuffer, &ppBufferOut, vecs);
							int size = S3MB::ImageOperator::Decode(texdata->m_nSize, texdata->m_nWidth, texdata->m_nHeight,&ppBufferOut, texdata->m_pBuffer, texdata->m_CompressType);
						}
					}
				}
			}
		}
	}

**Comment by muyan520** [comment]
http://ask.supermap.com/119876?show=119884

**Comment by heqianhq** [comment]
研发人员正在确认，有进展后会在这回复

**Comment by heqianhq** [comment]
可以直接调用ProcessTextureData()，将CodecType设置为encNONE, 但目前SDK只支持解压缩enrS3TCDXTN格式（即DXT格式）的数据。
