### ISSUE TITLE
如何对模型逐个顶点绑定id

### ISSUE THREAD

**Issue by nsj47** [SuperMap/s3m-spec#63]
你好，我下载了你们的sdk，里面有对立方体进行实例化渲染并指定id，我可以pick到每一个立方体。现在我不想用实例化，我怎样对每一个顶点进行id绑定，以便我可以对同一个geometry下的不同部位进行pick？

**Comment by pasu** [comment]
非实例化时可使用VertexDataPackage下vertexAttributeData属性设置每个顶点的属性值，比如id。

**Comment by nsj47** [comment]
你好，我在头文件中找到了VertexDataPackage的定义，以及它的真正实现VertexDataPackageTemplate，也找到了里面顶点数组纹理坐标等的存放位置。但我一直不能找到名称为vertexAttributeData的成员变量。我也尝试对整个目录进行搜索，依然找不到这个名称。能告诉我它在SDK中的具体位置吗？万分感谢

**Comment by pasu** [comment]
抱歉，我是指数据规范里面可以采用这种方式，但具体SDK中是否提供了对应接口，需要具体开发人员来确定，我开启这个问题，等开发人员具体了解后再答复。

**Comment by heqianhq** [comment]
你好， SDK中的VertexDataPackage中存有secondColor，与顶点一 一对应，可以用来存储id，与每个顶点绑定。
