### ISSUE TITLE
S3M数据解析过程中解压时报错

### ISSUE THREAD

**Issue by yieryi** [SuperMap/s3m-spec#64]
详细描述和问题反馈在 [http://ask.supermap.com/120364](http://ask.supermap.com/120364)

**Comment by heqianhq** [comment]
1）为什么config拿到的S3M描述版本号为2.0？
答：版本号为2.0是由于使用SuperMap GIS生成的就是S3M2.0版本的数据。目前，该仓库的解析源码是针对团标T/CAGIS 1—2019的S3M1.0，SuperMap GIS可生产S3M1.0、S3M2.0、S3M3.0三个版本的数据，不建议使用源码去解析S3M2.0和S3M3.0版本的数据。
2）当前s3mb解析过程中的解压失败是否是因为数据格式为2.0导致的？怎么解决或者这份数据应该怎样接入到原生Cesium环境下？
答：目前看来解析失败是由于数据版本为2.0导致的，建议通过SuperMap iClient3D for Cesium来解决该问题，SuperMap iClient3D for Cesium可通过http://support.supermap.com.cn/DownloadCenter/ProductPlatform.aspx获取。关于产品的使用问题可在超图问答社区提问。
3）S3M 2.0标准看起来没有公开，我没有搜索到任何有关的信息，官方是否有公开标准和解析方法的计划？
答：S3M2.0是SuperMap GIS内部的标准版本，暂时不对外公开。
4）官方针对 https://github.com/SuperMap/s3m-spec 仓库是否仍然维护，因为cesium.js新版本去掉when.js依赖，当前仓库状态无法适配最新版本的Cesium.js
答：官方一直在维护该仓库，相关工具和解析源码正在升级优化中，未来将会陆续上传。
