### ISSUE TITLE
现在是否支持 iDesketop X 处理的 s3m v1.0或V3.0的数据

### ISSUE THREAD

**Issue by alv1ns** [SuperMap/s3m-spec#70]
现在是否支持 iDesketop X 处理的 s3m v1.0或V3.0的数据，我本地测试是无法加载的，但iEarth可以加载

**Comment by heqianhq** [comment]
目前，本仓库提供的解析和加载工具包主要是针对S3M 1.0的数据，还不支持S3M 3.0。如果方便的话，可以提供下测试数据吗？

**Comment by alv1ns** [comment]
你好，数据在内网无法提取，您可以尝试用 最新版本的 iDesketop X 11i 将 OSGB 倾斜入库 然后再加载测试

**Comment by heqianhq** [comment]
收到，研发确认后再回复您

**Comment by heqianhq** [comment]
目前仓库已支持解析S3M 3.0数据。
