### ISSUE TITLE
s3m转3dtiles之后数据丢失

### ISSUE THREAD

**Issue by LuckyBrat** [SuperMap/s3m-spec#71]
原始手工模型是s3m格式的，转为3dtiles后，丢后
![转换前](https://github.com/SuperMap/s3m-spec/assets/57027681/6b02132a-afb6-4972-898d-8241853bc8bd)
![转换后](https://github.com/SuperMap/s3m-spec/assets/57027681/12d8e8d4-8f47-46ad-b39c-939402153b8b)

**Comment by heqianhq** [comment]
可否提供示例数据？
