### ISSUE TITLE
S3M_JS中选中模型对象后，如何设置选中的对象高亮

### ISSUE THREAD

**Issue by molly-github** [SuperMap/s3m-spec#73]
S3M_JS中选中模型对象后：
1. 如何设置选中的对象高亮；
2. 如何获取选中的模型对象属性信息；

**Comment by heqianhq** [comment]
问题1答复：示例代码并没有选中高亮的功能，在选中对象时可以拿到当前对象的id，通过batchid创建batchtable，来实现对id设置颜色，从而达到高亮效果。
问题2答复：属性信息可以通过获取到的id通过服务查询得到。
