### ISSUE TITLE
当前限制核实

### ISSUE THREAD

**Issue by DevLive2016** [SuperMap/s3m-spec#74]
刚下载使用中发现：
1：对于大疆智图等其他建模程序生成scp索引后 转换工具在创建部分后会崩溃 ：是仅支持CC的osgb吗？
2：对于 桌面 转出的 紧凑模式 或s3m 3/ 2 .无法预览，后期会加入支持吗？
3

**Comment by heqianhq** [comment]
1、目前是支持所有符合OSGB标准格式的数据。转换崩溃看是否能提供范例数据，我们进一步排查原因。
2、目前该工具目前不支持紧凑模式，目前暂未有更新计划。
关于解析S3M3.0和S3M2.0数据，目前仓库提供了两个版本的工具，原始版本工具（S3M_SDK_Lightweight package\Original）支持读写S3M1.0，读取S3M2.0。最新版本工具（S3M_SDK_Lightweight package\Latest）支持读写符合行标的数据，读取S3M3.0。可以选择对应版本的工具。如果选择工具版本正确，仍有问题，看是否能提供范例数据，我们进一步排查原因。
