### ISSUE TITLE
新版本写入函数，模型显示丢失贴图

### ISSUE THREAD

**Issue by daydayup-cpu** [SuperMap/s3m-spec#77]
新版的sdk，对s3m 3.0进行读写，模型贴图丢失，只显示白色，怎么解决呢
![屏幕截图 2024-01-07 214047](https://github.com/SuperMap/s3m-spec/assets/98039001/8f10c553-8f00-4718-858a-1be464961d21)

**Comment by heqianhq** [comment]
最新SDK写出的S3M数据是符合2023年9月17日发布的行标《空间三维模型瓦片数据格式》的规定，截图显示所用的SuperMap桌面软件是2022年发布的，尚未支持行标。您可以使用./S3M_SDK/S3M_JS，来实现数据在Web端的解析、加载。今年稍晚时间我们也会推出支持行标的桌面，届时可使用桌面来加载显示。

**Comment by daydayup-cpu** [comment]
行标是3.01版本，更改版本参数为3.0进行解析3.0版本的数据，现在的桌面端也不支持吗

**Comment by heqianhq** [comment]
目前最新版本桌面端产品是2023年9月发布的，不支持加载3.01版本的数据，即使修改了参数也无法解析的。2024年将会推出支持3.01版本的桌面端产品。

**Comment by daydayup-cpu** [comment]
我用了新版的./S3M_SDK/S3M_JS工具，示例数据（1.0版本）可以显示，但不显示3.0版本的数据，是有什么问题呢

**Comment by daydayup-cpu** [comment]
或者说，有什么办法可以对3.0版本的数据进行坐标的读取与写入呢

**Comment by heqianhq** [comment]
> 我用了新版的./S3M_SDK/S3M_JS工具，示例数据（1.0版本）可以显示，但不显示3.0版本的数据，是有什么问题呢

是否能提交测试数据，以便我们这边进行定位问题。

**Comment by heqianhq** [comment]
> 或者说，有什么办法可以对3.0版本的数据进行坐标的读取与写入呢

目前仓库的工具是不支持写S3M 3.0版本的数据。看能否将您的问题细化下，以便我们这边提供一个合适的解决方案？

**Comment by daydayup-cpu** [comment]
> > 或者说，有什么办法可以对3.0版本的数据进行坐标的读取与写入呢
> 
> 目前仓库的工具是不支持写S3M 3.0版本的数据。看能否将您的问题细化下，以便我们这边提供一个合适的解决方案？

我的需求是，可以对3.0数据的顶点坐标进行修改并写入，修改后的数据可以在supermap中正常显示、处理

**Comment by daydayup-cpu** [comment]
这是我所使用的3.0测试数据，使用新版S3M_JS工具，不能显示






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SuperMap/s3m-spec"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月9日(星期二) 下午2:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [SuperMap/s3m-spec] 新版本写入函数，模型显示丢失贴图 (Issue #77)





  
我用了新版的./S3M_SDK/S3M_JS工具，示例数据（1.0版本）可以显示，但不显示3.0版本的数据，是有什么问题呢
  
是否能提交测试数据，以便我们这边进行定位问题。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;


从QQ邮箱发来的超大附件

***@***.*** (221.67M, 2024年02月08日 14:40 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=72333938ef2144c59316ee79166653184f475b0c535104551a000b0b004b510f0605145a0652051a07520d0c5504545106550b5d30766175425a555c5908067774717d164a0f11370a&code=73980fa7

**Comment by heqianhq** [comment]
> > > 或者说，有什么办法可以对3.0版本的数据进行坐标的读取与写入呢
> > 
> > 
> > 目前仓库的工具是不支持写S3M 3.0版本的数据。看能否将您的问题细化下，以便我们这边提供一个合适的解决方案？
> 
> 我的需求是，可以对3.0数据的顶点坐标进行修改并写入，修改后的数据可以在supermap中正常显示、处理

我们这边了解了您的需求，但目前仓库主要是针对标准提供的工具，S3M 3.0是超图内部的格式，不对外公开具体细节。如果是项目的话，可以联系超图相关的支持人员。

**Comment by heqianhq** [comment]
> 这是我所使用的3.0测试数据，使用新版S3M_JS工具，不能显示
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "SuperMap/s3m-spec" ***@***.***&gt;; 发送时间:&nbsp;2024年1月9日(星期二) 下午2:14 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [SuperMap/s3m-spec] 新版本写入函数，模型显示丢失贴图 (Issue #77) 我用了新版的./S3M_SDK/S3M_JS工具，示例数据（1.0版本）可以显示，但不显示3.0版本的数据，是有什么问题呢 是否能提交测试数据，以便我们这边进行定位问题。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt; 从QQ邮箱发来的超大附件 ***@***.*** (221.67M, 2024年02月08日 14:40 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=72333938ef2144c59316ee79166653184f475b0c535104551a000b0b004b510f0605145a0652051a07520d0c5504545106550b5d30766175425a555c5908067774717d164a0f11370a&code=73980fa7

收到

**Comment by heqianhq** [comment]
> > 这是我所使用的3.0测试数据，使用新版S3M_JS工具，不能显示
> > […](#)
> > ------------------ 原始邮件 ------------------ 发件人: "SuperMap/s3m-spec" _**@**_._**>; 发送时间: 2024年1月9日(星期二) 下午2:14 _**@**_.**_>; _**@**_._**_**@**_.**_>; 主题: Re: [SuperMap/s3m-spec] 新版本写入函数，模型显示丢失贴图 (Issue #77) 我用了新版的./S3M_SDK/S3M_JS工具，示例数据（1.0版本）可以显示，但不显示3.0版本的数据，是有什么问题呢 是否能提交测试数据，以便我们这边进行定位问题。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: _**@**_._**> 从QQ邮箱发来的超大附件 _**@**_.**_ (221.67M, 2024年02月08日 14:40 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=72333938ef2144c59316ee79166653184f475b0c535104551a000b0b004b510f0605145a0652051a07520d0c5504545106550b5d30766175425a555c5908067774717d164a0f11370a&code=73980fa7
> 
> 收到



> 这是我所使用的3.0测试数据，使用新版S3M_JS工具，不能显示
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "SuperMap/s3m-spec" ***@***.***&gt;; 发送时间:&nbsp;2024年1月9日(星期二) 下午2:14 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [SuperMap/s3m-spec] 新版本写入函数，模型显示丢失贴图 (Issue #77) 我用了新版的./S3M_SDK/S3M_JS工具，示例数据（1.0版本）可以显示，但不显示3.0版本的数据，是有什么问题呢 是否能提交测试数据，以便我们这边进行定位问题。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt; 从QQ邮箱发来的超大附件 ***@***.*** (221.67M, 2024年02月08日 14:40 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=72333938ef2144c59316ee79166653184f475b0c535104551a000b0b004b510f0605145a0652051a07520d0c5504545106550b5d30766175425a555c5908067774717d164a0f11370a&code=73980fa7

已提交代码，可再使用验证下。但需要注意目前仓JS源码只支持解析纹理压缩格式为DXT的数据。
