### ISSUE TITLE
S3M_Parser_JS 加载倾斜摄影S3MB数据没有渲染

### ISSUE THREAD

**Issue by lzz616** [SuperMap/s3m-spec#8]
请问有试过用这个S3M_Parser_JS加载倾斜摄影的S3MB文件吗   我这边加载看到有下载S3MB文件 但是场景中没有渲染出来，模型的S3MB则可以正常渲染。

**Comment by pasu** [comment]
支持加载倾斜摄影数据，是否可以提供数据来验证？谢谢

**Comment by pasu** [comment]
S3M_Parser_JS只提供了对S3M切片数据的高效解析，用户需要根据自己的可视化场景来实现渲染部分的功能，并不涉及S3M_Parser_JS数据解析模块。如果还有问题，请开启issue并提供对应数据，我们来验证一下，谢谢。
