### ISSUE TITLE
加载s3m version2.0 纹理压缩格式为WEBP数据报错

### ISSUE THREAD

**Issue by qiujin8888** [SuperMap/s3m-spec#80]
报错信息如下
![image](https://github.com/SuperMap/s3m-spec/assets/20981306/6c074e40-0ebe-481b-ab75-f32c5d2abb51)

![image](https://github.com/SuperMap/s3m-spec/assets/20981306/1fde8131-6f12-424f-8431-fbc7ce96493c)

**Comment by heqianhq** [comment]
已提交修改

**Comment by qiujin8888** [comment]
谢谢，可以显示了

**Comment by heqianhq** [comment]
好的，那我关闭提问了。
