### ISSUE TITLE
.attribute 属性数据文件 

### ISSUE THREAD

**Issue by wangleiq** [SuperMap/s3m-spec#81]
.attribute 属性数据文件 存储格式是什么样的 和S3MD 属性数据文件有何区别  是如何解析的呢

**Comment by heqianhq** [comment]
.s3md采用JSON文件存储，并采用zip压缩。它是标准规定的格式，目前仓库中的工具和源码就支持直接解析。但.attribute是二进制的，是超图的内部格式，因此只能在SuperMap GIS系列产品中使用。
