### ISSUE TITLE
请问3.0的源码里，pagedlod节点只能挂载一个下层文件吗？

### ISSUE THREAD

**Issue by z386220349** [SuperMap/s3m-spec#82]
pagedlod节点里可以添加多个下层文件，但是write的时候只保存了一个，那如果我需要保存多个，我要怎么做呢
![11](https://github.com/SuperMap/s3m-spec/assets/115364467/af07bb5b-c3fe-4b14-9009-b8154d28aa5b)

**Comment by heqianhq** [comment]
每个pagedlod只能挂一个下层文件，如果要挂多个文件，建议创建多个pagedlod挂接文件。
