### ISSUE TITLE
这个代码迁到vue2.0 导致页面直接卡死崩溃

### ISSUE THREAD

**Issue by action9981** [SuperMap/s3m-spec#83]
`[<template>
    <div id="cesiumContainer" style="width: 100%; height: 70vh;"></div>
</template>

<script>
import S3MTilesLayer from './S3M_module/S3MTiles/S3MTilesLayer';
export default {
    name: 'CesiumMap',
    mounted() {
        // 确保 Cesium 全局对象可用
        // if (typeof Cesium !== 'undefined') {
        //     const viewer = new Cesium.Viewer(this.$el, {
        //         imageryProvider: new Cesium.IonImageryProvider({ assetId: 2 }),
        //         baseLayerPicker: false,
        //         geocoder: false
        //     });
        // } else {
        //     console.error('Cesium is not loaded');
        // }

        let viewer = new Cesium.Viewer('cesiumContainer',{
        });
        let scene = viewer.scene;
        let layer = new S3MTilesLayer({
            context : scene._context,
            url: '.D:\\work\\eserver\\supermap-s3m-load\\s3m-spec\\S3M_SDK\\S3M_JS\\data\\CBD\\cbd.scp'
        });

        scene.primitives.add(layer);

        layer.readyPromise.then(function() {
            scene.camera.setView({
                destination : new Cesium.Cartesian3(-2181968.890329965, 4385313.17843029, 4072712.8241634783),
                orientation : {
                    heading : 3.1756648661534443,
                    pitch : -0.3715184468182904
                }
            });
        }).otherwise(function(error) {
            console.log(error);
        });

    }
}
</script>
]

这里的 import 加入就崩溃 不加入 就没事import S3MTilesLayer from './S3M_module/S3MTiles/S3MTilesLayer';

**Comment by action9981** [comment]
`<template>
    <div id="cesiumContainer" style="width: 100%; height: 70vh;"></div>
</template>

<script>
import S3MTilesLayer from './S3M_module/S3MTiles/S3MTilesLayer';
export default {
    name: 'CesiumMap',
    mounted() {
        // 确保 Cesium 全局对象可用
        // if (typeof Cesium !== 'undefined') {
        //     const viewer = new Cesium.Viewer(this.$el, {
        //         imageryProvider: new Cesium.IonImageryProvider({ assetId: 2 }),
        //         baseLayerPicker: false,
        //         geocoder: false
        //     });
        // } else {
        //     console.error('Cesium is not loaded');
        // }

        let viewer = new Cesium.Viewer('cesiumContainer',{
        });
        let scene = viewer.scene;
        let layer = new S3MTilesLayer({
            context : scene._context,
            url: '.D:\\work\\eserver\\supermap-s3m-load\\s3m-spec\\S3M_SDK\\S3M_JS\\data\\CBD\\cbd.scp'
        });

        scene.primitives.add(layer);

        layer.readyPromise.then(function() {
            scene.camera.setView({
                destination : new Cesium.Cartesian3(-2181968.890329965, 4385313.17843029, 4072712.8241634783),
                orientation : {
                    heading : 3.1756648661534443,
                    pitch : -0.3715184468182904
                }
            });
        }).otherwise(function(error) {
            console.log(error);
        });

    }
}
</script>
`

**Comment by action9981** [comment]
<template>
    <div id="cesiumContainer" style="width: 100%; height: 70vh;"></div>
</template>

<script>
import S3MTilesLayer from './S3M_module/S3MTiles/S3MTilesLayer';
export default {
    name: 'CesiumMap',
    mounted() {
        // 确保 Cesium 全局对象可用
        // if (typeof Cesium !== 'undefined') {
        //     const viewer = new Cesium.Viewer(this.$el, {
        //         imageryProvider: new Cesium.IonImageryProvider({ assetId: 2 }),
        //         baseLayerPicker: false,
        //         geocoder: false
        //     });
        // } else {
        //     console.error('Cesium is not loaded');
        // }

        let viewer = new Cesium.Viewer('cesiumContainer',{
        });
        let scene = viewer.scene;
        let layer = new S3MTilesLayer({
            context : scene._context,
            url: '.D:\\work\\eserver\\supermap-s3m-load\\s3m-spec\\S3M_SDK\\S3M_JS\\data\\CBD\\cbd.scp'
        });

        scene.primitives.add(layer);

        layer.readyPromise.then(function() {
            scene.camera.setView({
                destination : new Cesium.Cartesian3(-2181968.890329965, 4385313.17843029, 4072712.8241634783),
                orientation : {
                    heading : 3.1756648661534443,
                    pitch : -0.3715184468182904
                }
            });
        }).otherwise(function(error) {
            console.log(error);
        });

    }
}
</script>

**Comment by heqianhq** [comment]
好的，研发正在看，后续有修改会更新。

**Comment by heqianhq** [comment]
可以通过去掉源码中的混淆代码来解决该问题，具体操作如下：在S3ModelParser.js文件中将下面引用注释掉，并注释代码中使用的地方即可。需要注意：经过该操作后，可以加范例数据，但不支持加Draco和MeshOPT压缩的数据。
![图片1](https://github.com/SuperMap/s3m-spec/assets/47965545/ebfc4337-ede3-49a4-b8c6-13ca0e42ad31)
