### ISSUE TITLE
编译ConvertTool/Latest/S3MBToolkit失败

### ISSUE THREAD

**Issue by wu007kun** [SuperMap/s3m-spec#85]
操作系统：win11 x64
我想使用S3MBToolkit用于转换s3mb到obj
在win11下尝试编译，遵循这一步骤：
“进入./S3MBToolkit/3rdParty文件夹，运行CMake脚本，编译生成需要的第三方库。”

运行cmake成功，但进一步运行make时，出现一些问题。
1. 首先是从github拉取pcre，由于以往的master分支变为了main分支，出现一些问题，已经手动解决了
2. 再次make，出现如下报错：
CMake Error: The source directory "xxxx/ConvertTool/Latest/S3MBToolkit/3rdParty/pcre/src/pcre" does not appear to contain CMakeLists.txt.
报错中指出的这个目录3rdParty/pcre/src/pcre，是pcre的代码仓库，这看起来是一个php项目，报错信息说这个目录下没有CMakeLists.txt

**Comment by heqianhq** [comment]
收到，研发确认后回复

**Comment by heqianhq** [comment]
已提交修改，可以再尝试下是否可以。

**Comment by wu007kun** [comment]
> 已提交修改，可以再尝试下是否可以。

十分感谢，此问题已经解决

**Comment by yljxhh** [comment]
@wu007kun 你好，请问下你在Windows上用的Visual Studio哪个版本编译通过呢？我用的2019报了一堆错误

**Comment by UserNameQC** [comment]
@yljxhh 我也是，搞不出来了，后来可以了吗

**Comment by HiXiSi** [comment]
> @yljxhh 我也是，搞不出来了，后来可以了吗

当时pcre这个问题解决了，但是后续还有一堆问题，感觉没什么希望能编译成功，最后放弃了

**Comment by yljxhh** [comment]
> @yljxhh 我也是，搞不出来了，后来可以了吗

没有，搞了几天，解决一个问题，还有其他一大堆问题，放弃了

**Comment by yljxhh** [comment]
> @yljxhh 我也是，搞不出来了，后来可以了吗

没有，一大堆错误，后面我也放弃了
