### ISSUE TITLE
3.0 代码里 ToStandardType 函数有问题

### ISSUE THREAD

**Issue by FelixYuanSpace** [SuperMap/s3m-spec#91]
![image](https://github.com/SuperMap/s3m-spec/assets/155788126/9b3cd329-e95d-4814-94d5-b4917fde33b2)
这地方写错了吧，switch用eFormat?不是nFormat？判断完了自己，再给自己赋值~

**Comment by heqianhq** [comment]
收到，确认后回复

**Comment by heqianhq** [comment]
已提交修改
