### ISSUE TITLE
我们从超图iDesktop弄到一组数据，压缩算法nCompressType是26，但是目前s3m C++的3.0 SDK里面并没有提供出这个压缩算法是个啥协议

### ISSUE THREAD

**Issue by FelixYuanSpace** [SuperMap/s3m-spec#93]
![5b9878559195067e429daf64347f7f5](https://github.com/SuperMap/s3m-spec/assets/155788126/84abeaba-78ad-4dd7-940f-34f107b47744)
这是我们数据的读出来的压缩算法nCompressType的值是26，但是代码里没有26对应的算法协议，所以我们无法读出该材质图片，ToStandardType内代码当前是这样：
![09d79a04d95b9ceb3553456b73ddabb](https://github.com/SuperMap/s3m-spec/assets/155788126/42c7a019-06ac-4df4-b867-348e9b8734b9)
请官方给出解释吧

**Comment by heqianhq** [comment]
收到，确认后回复

**Comment by heqianhq** [comment]
该压缩方式是SuperMap iDesktopX生成S3M瓦片时选择的CRN_DXT5，目前C++解析源码并未支持，但JS源码支持解析。

**Comment by StoneHao** [comment]
> 该压缩方式是SuperMap iDesktopX生成S3M瓦片时选择的CRN_DXT5，目前C++解析源码并未支持，但JS源码支持解析。

那么什么时候 C++ SDK 可以支持解析呢
