### ISSUE TITLE
CMake Error at E:\Work\VSWork\s3m-spec\ConvertTool\Latest(行标）\S3MBToolkit\CMakeLists.txt:86 (target_link_libraries)

### ISSUE THREAD

**Issue by UserNameQC** [SuperMap/s3m-spec#94]
CMake Error at E:\Work\VSWork\s3m-spec\ConvertTool\Latest(行标）\S3MBToolkit\CMakeLists.txt:86 (target_link_libraries):
  Target "s3m" of type UTILITY may not be linked into another target.  One
  may link only to INTERFACE, OBJECT, STATIC or SHARED libraries, or to
  executables with the ENABLE_EXPORTS property set.	S3MBToolkit	E:\Work\VSWork\s3m-spec\ConvertTool\Latest(行标）\S3MBToolkit\CMakeLists.txt	86	

这种是什么问题，按照readme进行编译的，工具是VS 2019,

**Comment by heqianhq** [comment]
已提交修改
