### ISSUE TITLE
BUG: 64位操作系统 FileUtils::ListFiles 异常

### ISSUE THREAD

**Issue by yuz1** [SuperMap/s3m-spec#96]
https://github.com/SuperMap/s3m-spec/blob/9c15ed9c7c50b47f7898fb629bb72d46a9a5c269/ConvertTool/Latest(%E8%A1%8C%E6%A0%87%EF%BC%89/S3MBToolkit/S3MBToolkit/Src/Utils.cpp#L705

long的范围不够,
当系统是32位 _wfindfirst 返回的是int32类型  long
当系统是64位 _wfindfirst 返回的是int64类型  long long ,
建议改为:
auto lIsFindFile = _wfindfirst(strPathName.c_str(), &c_file);

**Comment by heqianhq** [comment]
采纳建议，已提交修改

**Comment by yuz1** [comment]
@heqianhq 改错了。
auto lIsFindFile = -1;
lIsFindFile = _wfindfirst(strPathName.c_str(), &c_file);
和
auto lIsFindFile = _wfindfirst(strPathName.c_str(), &c_file);
是不一样的。

**Comment by heqianhq** [comment]
> @heqianhq 改错了。 auto lIsFindFile = -1; lIsFindFile = _wfindfirst(strPathName.c_str(), &c_file); 和 auto lIsFindFile = _wfindfirst(strPathName.c_str(), &c_file); 是不一样的。

已修改
