### ISSUE TITLE
报一个可能导致内存泄露的bug

### ISSUE THREAD

**Issue by elfc2000** [SuperMap/s3m-spec#99]
S3MBTools.cpp这句话，delete 方式不对，应该delete[] 
![微信截图_20241128102458](https://github.com/user-attachments/assets/45b261e3-d32b-4964-8f9c-bfde478812a7)

**Comment by heqianhq** [comment]
为规范代码，已提交修改

**Comment by heqianhq** [comment]
为规范代码，已提交修改
